# Generated by Django 5.1.3 on 2024-12-01 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('color', models.CharField(blank=True, default='#808080', max_length=7, null=True)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('customerQuantity', models.IntegerField(blank=True, null=True)),
                ('clubArea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapdesigner.clubarea')),
            ],
        ),
    ]
