# Generated by Django 5.1.3 on 2024-12-06 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdesigner', '0004_mapobject_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(blank=True, default=800, null=True)),
                ('height', models.FloatField(blank=True, default=500, null=True)),
                ('club_area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mapdesigner.clubarea')),
            ],
        ),
    ]
