# Generated by Django 5.1.3 on 2024-12-06 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdesigner', '0005_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapobject',
            name='clubArea',
        ),
        migrations.RemoveField(
            model_name='map',
            name='club_area',
        ),
        migrations.AddField(
            model_name='map',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='name',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='mapobject',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapdesigner.map'),
        ),
        migrations.DeleteModel(
            name='ClubArea',
        ),
    ]
