# Generated by Django 5.1.3 on 2024-12-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdesigner', '0007_mapobject_rotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapobject',
            name='rotation',
            field=models.IntegerField(default=0),
        ),
    ]
