# Generated by Django 5.1.3 on 2024-12-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdesigner', '0008_alter_mapobject_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapobject',
            name='height',
            field=models.FloatField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='mapobject',
            name='width',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
    ]
