# Generated by Django 5.1.3 on 2024-11-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottle',
            old_name='bottle_type',
            new_name='type_bottle',
        ),
    ]
