# Generated by Django 5.1.3 on 2024-11-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_rename_bottle_type_bottle_type_bottle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottle',
            old_name='type_bottle',
            new_name='typeBottle',
        ),
    ]
