# Generated by Django 5.1.3 on 2024-11-30 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_rename_type_bottle_bottle_typebottle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='quantity',
        ),
        migrations.AddField(
            model_name='bottle',
            name='quantity_in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BottlePurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='warehouse.bottle')),
            ],
        ),
    ]
